POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email": "lucas7justino@gmail.com",
    "username": "lucasjstn",
    "password": "fate1928"
}

### SignIn
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "username": "lucasjstn",
    "password": "fate1928"
}

### WhoAmI
GET http://localhost:3001/auth/whoami
